### ISSUE TITLE
Priority too low when unstaking all

### ISSUE THREAD

**Issue by Inquinim** [RaoFoundation/subtensor#171]
When trying to unstake all hotkeys I get this error sometimes.

`SubstrateRequestException: {'code': 1014, 'message': 'Priority is too low: (18446744073709551615 vs 18446744073709551615)', 'data': 'The transaction has too low priority to replace another transaction already in the pool.'}`

I need to restart the entire unstake all operation from the start. It would be great if the error can be caught and it will retry again after a short while.

**Comment by camfairchild** [comment]
@Inquinim I transferred the issue to the Subtensor repo because this is an issue with the chain

**Comment by tavurth** [comment]
@camfairchild where is that issue? I'm seeing this issue now (`transfer.extrinsic`) on `Bittensor 7.2.0`

Opened a specific issue for it:

https://github.com/opentensor/subtensor/issues/641
