### ISSUE TITLE
Incorrect miner deregistration priority

### ISSUE THREAD

**Issue by ppolewicz** [RaoFoundation/subtensor#235]
### Describe the bug

look at steps to reproduce and expected behavior

### To Reproduce

1. Register miners 1-N that do nothing where N>more than subnet limit (currently 256)
2. See that the first miner that gets unregistered is not necessarily the oldest miner that registered

### Expected behavior

The miners for deregistration should be sorted by (emission, registration_time), so if both miners have the same emission, the one that registered earlier on should be ejected first. It was observed in the wild on sn12 mainned that this is not the case and in presence of 120 miners that do nothing, a relatively fresh one was ejected a day after it registered.

### Environment

linux

**Comment by distributedstatemachine** [comment]
Closed in #726
