### ISSUE TITLE
Trust minimized (light client) interconnect with Cosmos SDK 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [RaoFoundation/subtensor#238]
### Is your feature request related to a problem? Please describe.

How to call subtensor from Cosmos SDK?

### Describe the solution you'd like

Integrate IBC pallet which is trust minimized (light client based) way to call subtensor from cosmos-sdk and other ibc enabled chains.

Here is example https://github.com/ggxchain/ibc/blob/main/ibc-ggx-cosmos%20ICF%20M3%20deliverabl.md

### Describe alternatives you've considered

Offchain solutions.

**Comment by distributedstatemachine** [comment]
Hey @dzmitry-lahoda ! Thanks for reaching out .

This is not something we currently have on our roadmap. 

Can you please expand on your usecase?
