### ISSUE TITLE
Add proxy pallet to the subtensor layer

### ISSUE THREAD

**Issue by scucchiero** [RaoFoundation/subtensor#239]
### Is your feature request related to a problem? Please describe.

Currently, the Subtensor layer doesn't include the proxy pallet which is a key feature for delegating operations securely such as staking to a third party.

### Describe the solution you'd like

Include the proxy pallet to the subtensor layer.

**Comment by distributedstatemachine** [comment]
This will be added in https://github.com/opentensor/subtensor/pull/286

**Comment by scucchiero** [comment]
@distributedstatemachine Thank you very much for reviewing this and for taking the time to point towards the PR. 

I wonder if you may have a rough estimate for when that change will be on main/production? This would help us prioritise on our end.

Thanks in advance!

**Comment by distributedstatemachine** [comment]
@sam0x17 probably has a better idea of this

**Comment by sam0x17** [comment]
@scucchiero about a week. It's on `devnet` now still needs to go on `testnet`, and we are revamping our deploy process early this week.
