### ISSUE TITLE
Eliminate warnings from compilation

### ISSUE THREAD

**Issue by mvds00** [RaoFoundation/subtensor#247]
### Is your feature request related to a problem? Please describe.

I generally don't like (production) code to compile with warnings, and I get quite a few of them compiling subtensor with default settings. Would it be an idea to eliminate them? Most of the current warnings seem easy enough to eliminate. Some of them are hard to understand without in-depth knowledge of rust and substrate.

### Describe the solution you'd like

I would like to work together on this, e.g. by submitting a PR and iteratively working toward a warning-free build. At some point the equivalent of `-Werror` (in C) could be enabled in the default build settings.

First I would like to know if such a PR has any chance of being accepted.

**Comment by gregzaitsev** [comment]
Addressed in [PR-257](https://github.com/opentensor/subtensor/pull/257)
