### ISSUE TITLE
README.md cargo build command misses a flag

### ISSUE THREAD

**Issue by mvds00** [RaoFoundation/subtensor#261]
### Describe the bug

Building subtensor leads to a non-functioning binary (with fatal errors such as `"runtime requires function imports which are not present on the host: 'env:ext_benchmarking_current_time_version_1'"`) which is solved by adding `--features=runtime-benchmarks` as mentioned in the Discord. It would be nice if the README would reflect this requirement.

### To Reproduce

1. Go to https://github.com/opentensor/subtensor
2. Follow the build instructions, especially `cargo build --release`
3. Run the subtensor
4. Observe it crashing with error `"runtime requires function imports which are not present on the host: 'env:ext_benchmarking_current_time_version_1'"`

### Expected behavior

I expect a working binary after performing the build instructions.

### Environment

Linux Ubuntu

### Additional context

It seems to be solved by adding `--features=runtime-benchmarks` to the `cargo build` command.

**Comment by hamletwasntfat** [comment]
This bug still relevant.
