### ISSUE TITLE
Bittensor Archive node stuck at block 2585474

### ISSUE THREAD

**Issue by AlexZhenWang** [RaoFoundation/subtensor#274]
### Describe the bug

Hi, I'm currently operating a Bittensor node, and it seems to be stuck at block 2585474.

The logs indicate that the best block remains at 2585476, while the finalized block remains at 2585474. Does anyone have any suggestions on how to resolve this issue?

Additionally, I would greatly appreciate it if someone could provide the p2p address of a node that has successfully passed this block. I'd like to try using it as a peer for my node to see if it helps resolve the problem.

Thank you in advance for any assistance!

### To Reproduce

1. Run a bittensor archive node
with parameters
```
--base-path=/chain-data
--rpc-cors=all
--port=20540
--rpc-port=9933
--ws-port=9944
--ws-external
--rpc-external
--node-key=bb86e433fe0f1f662a6fdf93211d21fa1e72537865f2f58ddec8e63d6eab3348
--pruning=archive
--rpc-methods=Unsafe
--in-peers=25
--out-peers=25
--prometheus-external
--chain=/raw_spec.json
--in-peers-light=0
--max-runtime-instances=128
--ws-max-connections=10000
```

### Expected behavior

Expect the node to keep syncing the latest block

### Environment

Ubuntu VERSION="20.04.6 LTS (Focal Fossa)"

**Comment by AlexZhenWang** [comment]
Move this to bittensor repo

**Comment by Peterwang366** [comment]
@AlexZhenWang hey buudy，I also encountered the same problem, have you solved it?
