### ISSUE TITLE
./target/release/subtensor: No such file or directory

### ISSUE THREAD

**Issue by GuiFlam** [RaoFoundation/subtensor#283]
### Describe the bug

After building with the command : cargo build --release
And running the build with : ./target/release/subtensor --dev, I get the error: -bash: ./target/release/subtensor: No such file or directory. When I looked in the /target/release folder, there is no subtensor file, but there is a node-subtensor file.

### To Reproduce

build with the command cargo build --release
run the build with the command ./target/release/subtensor --dev

### Expected behavior

The build should be successful

### Environment

Linux Ubuntu

**Comment by distributedstatemachine** [comment]
Hey @GuiFlam ! 

Thanks for reaching out . The our docs for running this locally were temporarily out of sync , and its been fixed here: https://github.com/opentensor/subtensor/pull/316 .

Please try it out and let us know how you get along
