### ISSUE TITLE
Subtensor Nodes Persistently Attempt to Connect to Unavailable Services

### ISSUE THREAD

**Issue by wolfentensor** [RaoFoundation/subtensor#306]
### Describe the bug

Subtensor nodes continue to attempt connections to services that have become unavailable, persisting even after those services explicitly refuse connections or stop responding. This issue has been observed over a period of 7 days, during which a service initially returned TCP RST packets for 5 days before completely ceasing to respond for an additional 2 days.

### To Reproduce

1. Set up a node using the Bittensor Subtensor package.
2. Allow the node to operate normally and connect to other nodes.
3. Shut down one of the services or nodes it connects to, ensuring it either sends TCP RST packets back or stops responding altogether.
4. Observe the behavior of the Subtensor node trying to connect to the now unavailable service over several days.

### Expected behavior

The Subtensor node should cease its attempts to connect to a service that has consistently been unavailable or explicitly refused connections over a reasonable period.

**Actual Behavior:**
The Subtensor node persists in attempting to connect to the service, sending TCP SYN packets continuously without recognizing the service's unavailability. This behavior persists over an extended period, observed for at least 7 days in this instance.

### Screenshots

![Screenshot from 2024-04-08 11-26-20](https://github.com/opentensor/subtensor/assets/157622660/47562951-5dd5-4c40-8d67-edbb94dc6e81)
![Screenshot from 2024-04-08 11-29-38](https://github.com/opentensor/subtensor/assets/157622660/742fa662-4302-459d-836a-c9e36675ee59)

### Environment

Debian Linux 11, Subtensor v0.0.1, Docker v25.0.4

### Additional context

- **Persistent Connection Attempts:** The behavior was first noticed when a service was intentionally shut down, returning TCP RST packets for 5 days. Following this period, the port was blocked to stop responding altogether, yet Subtensor nodes continued their connection attempts for at least 2 more days.
- **Network Resource Wastage:** The continuous attempts to connect to an unavailable service can lead to unnecessary network traffic, consuming bandwidth and potentially degrading the performance of nodes involved in these futile connection attempts.
- **Potential Latency Increase:** The persistent attempts and subsequent network congestion could introduce latency in the network, affecting the overall performance and responsiveness of the Bittensor network.
- **Risk of Blacklisting**: Continuous, unwarranted connection attempts to external services or nodes could result in Subtensor nodes being blacklisted by network administrators or automated security systems, isolating them from parts of the internet and hindering the network's functionality and reach.

**Comment by open-junius** [comment]
@wolfentensor based on the info, it is difficult to see the problem from which layer. I just tried build connection and disconnected in local env. The connection is removed from swarm but the peer stay in the peerset but reputation is lower and lower. 
Could you please get some log for me from live network, it will be helpful for me to investigate.
logs I need from modules as follows. you can set RUST_LOG="module-name=trace,"
sub-libp2p
sync
gossip
peerset
libp2p-dns
libp2p-kad
libp2p-tcp
libp2p-swarm

**Comment by sam0x17** [comment]
will re-open if/when there are updates from @wolfentensor
