### ISSUE TITLE
Latest status: Subtensor node installation instructions

### ISSUE THREAD

**Issue by rajkaramchedu** [RaoFoundation/subtensor#310]
### Describe the bug

I am opening this issue to report the latest status on subtensor node installation steps:

1. In this repo this section of the README needs fixing: https://github.com/opentensor/subtensor?tab=readme-ov-file#run-in-docker (there is no script called `./scripts/docker_run.sh`).
2. Instructions in this Discord announcement thread are cleaner and they are working. I tested them okay. https://discord.com/channels/799672011265015819/830075335084474390/1219185730564390922 
3. These instructions in this repo need fixing (it says "docker" for compiling with source code): https://github.com/opentensor/subtensor/blob/development/docs/running-subtensor-locally.md#running-the-node
4. For my docs at docs.bittensor.com, I cleaned up all this, removed using the script for the source code option and created a new Subtensor section: https://github.com/opentensor/developer-docs/pull/192 I used Discord announcement instructions in these docs.
5. If you are okay with it, I can take a shot at fixing the README and other docs in this repo. I will wait for your signal. 

### To Reproduce

See above description.

### Expected behavior

See above description.

### Environment

macOS

**Comment by distributedstatemachine** [comment]
Hey @rajkaramchedu !

Thanks for filing this . More than happy for you to submit a PR for this !

**Comment by rajkaramchedu** [comment]
@distributedstatemachine hey, thanks! I am blocked. See the Discord message: https://discord.com/channels/799672011265015819/1176889798313660476/1227772960907989023

**Comment by rajkaramchedu** [comment]
https://github.com/opentensor/subtensor/pull/316

**Comment by distributedstatemachine** [comment]
@rajkaramchedu since this is in the development branch , can we close it ?

**Comment by rajkaramchedu** [comment]
Yes, closing.
