### ISSUE TITLE
Issue setting up a node to run on testnet

### ISSUE THREAD

**Issue by sam0x17** [RaoFoundation/subtensor#342]
Copied from @rajkaramchedu:

1) I believe running subtensor node for mainnet is okay, no complaints there. 
2) But whenever a user wants to run the node on testnet, for some reason it keeps going to mainnet, is what they are saying. 
3) It may be as simple as one of the nucleus team members to look at testchain command syntax for both "using source" and "using docker" sections of the doc and help identify what's wrong with those command options. Maybe the bootnode public key is wrong for the testnet? https://docs.bittensor.com/subtensor-nodes/using-source#lite-node-on-testchain
[3:51 PM]
Latest issue the user is facing is from a few mins ago https://discord.com/channels/799672011265015819/1228380578949369947/1230596951381119079. This is all familiar, we've been getting these questions since almost 2+ weeks ago.
[3:53 PM]
This issue resolution alone will reduce a good number of subtensor node related questions in the community.
Doc Issue on this https://github.com/opentensor/developer-docs/issues/188

**Comment by rajkaramchedu** [comment]
One user gave up on testnet and went directly to mainnet due to this issue. Linking Discord message just as fyi. https://discord.com/channels/799672011265015819/1228380578949369947/1231302939797229660

**Comment by rajkaramchedu** [comment]
More heartache: https://discord.com/channels/799672011265015819/1228380578949369947/1231617231616606258

**Comment by open-junius** [comment]
The root cause is the spec and bootnode in the doc is wrong.
1. for testnet, we should use the raw_testspec.json or raw_spec_testfinney.json
2. the bootnode in the cli for testnet is the same on with mainnet, except with the dns prefix.

we need update the doc.

**Comment by rajkaramchedu** [comment]
So @open-junius in https://docs.bittensor.com/subtensor-nodes/using-source#lite-node-on-testchain section and for archive node also all I have to do is to fix the "--chain raw_spec.json" to one of the two you mentioned, correct? The boot node for the testchain in these two cases, lite and archive, looks correct to you? 

Also has anyone run the node with testchain settings you said and confirmed it works? I am on mobile now so can't run it now. Thanks!

**Comment by open-junius** [comment]
the bootnode for lite and archive should be the same for testnet. I will ask team to get a correct bootnode in testnet. then will try it by self.

**Comment by open-junius** [comment]
/dns/bootnode.test.finney.opentensor.ai/tcp/30333/p2p/12D3KooWPM4mLcKJGtyVtkggqdG84zWrd7Rij6PGQDoijh1X86Vr is the correct boot node. And from our docker-compose.yml file, we can find out the correct spec as well. just need to update the doc
