### ISSUE TITLE
Add limit on number of nominators to delegates to limit cost of distribution.

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#347]
Status as of 2024-04-19: The code partially implemented in stao branch:
1. Not enforced
2. Need a state map to store nominator counters to avoid O(1) iterations in the extrinsics.
3. Migration
4. Tests

**Comment by gztensor** [comment]
The [PR #367](https://github.com/opentensor/subtensor/pull/367) closes this issue

**Comment by gztensor** [comment]
The [PR #370](https://github.com/opentensor/subtensor/pull/370) removes these changes from dynamic
