### ISSUE TITLE
DTAO Community Server

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#392]
## Description 

In order for the community to familiar themselves with DTAO and its concepts , we will be setting a server with a local node set up running the `dynamic` branch of substensor. 

## Acceptance Criteria

- It should allow connections to both the cli and polkadot.js explorer. 
- It should expose a websocket port of over DNS.

**Comment by gztensor** [comment]
Up and running: wss://dtao-demo.chain.opentensor.ai:443

**Comment by distributedstatemachine** [comment]
Closed at Stale
