### ISSUE TITLE
Investigate a funding mechanism for registering a subnet lock cost

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#414]
## Description
Investigate the subnet lock cost and potential changes to its structure

### Background
> https://github.com/opentensor/subtensor/issues/294  
>
> Currently, if a subnet owner registers on mainnet, the cost for the subnet is **locked**, but not recycled. So if the subnet fails, the only people significantly affected are the miner and validator operators, who have recycled TAO to register within the subnet. I feel as if the price of failure to launch a subnet and gain emissions from the root network should actually be a *price*.
>
> I would like to see the subnet registration either:
>
>    1. Be recycled, instead of locked
>    2. Locked, but then apportioned out to the participants in the subnet according to the last know emissions schedule (18% for the owner, 82% for the node operators).
#### What a good solution looks like
1. Provides a stronger disincentive to subnet owners that lose their registration
2. Reduces the impact on individual subnet registrants
#### Initial Ideas
1. The subnet registration cost should be recycled instead of locked
   a. All of the registration cost should be recycled
   b. A portion of the registration cost should be recycled, the rest locked
2. A portion of the subnet registration cost should remain locked, with the rest distributed to the subnet registrants proportionally by some metric
   a. The distribution should happen by the instantaneous emission at the block of deregistration
   b. The distribution should happen by the average emission in the blocks before deregistration 
   c. The distribution should happen evenly across all registrants
   d. The distribution should happen based on stake-weight and incentive, similar to 2a. (i) or 2b. (ii)

## Related Links

- https://github.com/opentensor/subtensor/issues/294

**Comment by gztensor** [comment]
Feels like with DTAO this problem goes away because

1. There's no lock cost anymore
2. Subnets don't dissolve

The only risk here is that subnet is not going to be profitable for miners/validators who registered on it, but I think this risk is out of scope for the problem statement.

**Comment by gztensor** [comment]
Also, the STAO -> DTAO transition unlocks the locked TAO for subnet and returns it to the creator (except it reserves 1 TAO for initializing dynamic pool)
