### ISSUE TITLE
Improve error granularity

### ISSUE THREAD

**Issue by sam0x17** [RaoFoundation/subtensor#422]
Right now a lot of the errors returned by subtensor extrinsics are fairly generic substrate errors. We want these to be as granular / descriptive as possible, so an audit of what errors we are returning should be conducted and we should create new error types and/or utilize existing descriptive ones wherever possible

A/C:
- [ ] review the errors we currently return
- [ ] add new errors and/or replace generic errors with specific ones
- [ ] coordinate with @opentensor/cortex to make sure `bittensor` is ready for these changes
- [ ] profit?

**Comment by basfroman** [comment]
I have already implemented the [logic for retrieving error data](https://github.com/opentensor/bittensor/blob/staging/bittensor/subtensor.py#L4517) (name and description) from SubstrateInterface metadata. However, we don't know if all errors on the Subtensor side return an error number/index.

Here is the [card](https://github.com/opentensor/bittensor/issues/1859) associated with this implementation.
