### ISSUE TITLE
Integrate Ledger support

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#428]
# Ledger App support
Zondax et al. have developed a Ledger app to support generic substrate networks,[^1] meaning Bittensor will benefit from this app provided we integrate the required changes to our runtime, giving us Ledger support (and other hardware signers).

The changes required involve providing a verification of the chain metadata to consumers, e.g. hardware signers. This change allows hardware signer devices to verify their decoding of transactions, avoiding approvals of maliciously crafted transactions given some unverified metadata. 

[^1]: https://zondax.ch/blog/the-generic-polkadot-ledger-app-proposal
## Background
- Overview forum post: <https://forum.polkadot.network/t/polkadot-generic-ledger-app/4295/3>
- RFC for needed runtime changes: <https://github.com/polkadot-fellows/RFCs/pull/46>
- `polkadot-sdk` Upstream PR: https://github.com/paritytech/polkadot-sdk/pull/4274
- [Guide for integration](https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_metadata_hash/index.html)

## TODO (from above guide)[^2]:
[^2]: [Guide for integration](https://github.com/paritytech/polkadot-sdk/blob/a6dee1618b580c421d9970f690c0e10f71e7d170/docs/sdk/src/guides/enable_metadata_hash.rs)
- [x] Runtime integration
> From the runtime side only the `frame_metadata_hash_extension::CheckMetadataHash` needs to be added to the [list of signed extension[s]](https://github.com/paritytech/polkadot-sdk/blob/a6dee1618b580c421d9970f690c0e10f71e7d170/templates/parachain/runtime/src/lib.rs#L78-L90)
>> **Note:**
>>
>> Adding the signed extension changes the encoding of the transaction and adds one extra byte per transaction!
>
> This signed extension will make sure to decode the requested `mode` and will add the metadata
> hash to the signed data depending on the requested `mode`. The `mode` gives the user/wallet
control over deciding if the metadata hash should be verified or not. The metadata hash itself
> is drawn from the `RUNTIME_METADATA_HASH` environment variable. If the environment variable is
> not set, any transaction that requires the metadata hash is rejected with the error
> `CannotLookup`. This is a security measurement to prevent including invalid transactions.
>
> ### Warning
> The extension does not work with the native runtime, because the
> `RUNTIME_METADATA_HASH` environment variable is not set when building the
> `frame-metadata-hash-extension` crate.

- [x] Enable metadata hash generation
> The metadata hash generation needs to be enabled when building the wasm binary. The [`substrate-wasm-builder` supports this out of the box](https://github.com/paritytech/polkadot-sdk/blob/a6dee1618b580c421d9970f690c0e10f71e7d170/templates/parachain/runtime/build.rs#L1C1-L7C1)
>
>> **Note:**
>>
>> The `metadata-hash` feature needs to be enabled for the `substrate-wasm-builder` to enable the
>> code for being able to generate the metadata hash. It is also recommended to put the metadata
>> hash generation behind a feature in the runtime as shown above. The reason behind is that it
>> adds a lot of code which increases the compile time and the generation itself also increases
>> the compile time. Thus, it is recommended to enable the feature only when the metadata hash is
>> required (e.g. for an on-chain build).
>
> The two parameters to `enable_metadata_hash` are the token symbol and the number of decimals of
> the primary token of the chain. These information are included for the wallets to show token
> related operations in a more user friendly way.

**Comment by camfairchild** [comment]
Also requires a change to client-code, notably https://github.com/opentensor/bittensor
See: https://github.com/opentensor/bittensor/pull/2156
