### ISSUE TITLE
Add migration to populate SubnetCreator

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#436]
A new state map was added in DTAO and needs a migration to be populated: 

SubnetCreator::<T>::insert(netuid_to_register, hotkey.clone()); // Set the creator hotkey (which is forever.)'''

**Comment by gztensor** [comment]
Done.

The migration to populate SubnetCreator:
https://github.com/opentensor/subtensor/blob/de987e32bccdd3e8cc15141cf030eaa6245d1dcd/pallets/subtensor/src/migration.rs#L539

Making it run on the network update:
https://github.com/opentensor/subtensor/blob/de987e32bccdd3e8cc15141cf030eaa6245d1dcd/pallets/subtensor/src/lib.rs#L1368

**Comment by distributedstatemachine** [comment]
Closed at Stale

**Comment by distributedstatemachine** [comment]
Closed at Stale
