### ISSUE TITLE
Fix the raw_spec.json and node start commans

### ISSUE THREAD

**Issue by open-junius** [RaoFoundation/subtensor#461]
### Describe the bug

The raw_spec is broken, not a valid json file. The commands in the doc include the deprecated parameters and wrong node id.

### To Reproduce

Follow the docs/running-subtensor-locally.md, we can connect to testnet and mainnet.

### Expected behavior

connect to testnet and mainnet, sync up blocks.

### Environment

MacOS

**Comment by distributedstatemachine** [comment]
completed in #460
