### ISSUE TITLE
NotEnoughStaketoWithdraw erorr on `btcli st undelegate --all`

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#466]
steps to reproduce:

Setup 2 wallets with balances (btcli w create, btcli w faucet)
Create a subnet with wallet 1
`btcli root register` - become delegate (from wallet 1)
btcli st delegate - delegate 1000 from wallet 2
Wait until the next epoch - staked balance gets up to 1099...
btcli at undelegate --all - undelegate full amount fails

**Comment by gztensor** [comment]
Fixed in `dynamic` branch of bittensor

**Comment by camfairchild** [comment]
See: https://github.com/opentensor/subtensor/pull/462 for fix on finney

**Comment by distributedstatemachine** [comment]
Closed at Stale
