### ISSUE TITLE
Bug: Total Issuance reduced, while TAO is not burned in `clear_small_nomination_if_required`

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#495]
`add_balance_to_coldkey_account` is called here: 
https://github.com/opentensor/subtensor/blob/86b7f6dd702cf173ca98d683d6d01cc402ea9854/pallets/subtensor/src/staking.rs#L704

so the cleared_stake TAO doesn't disappear, it is credited back to the coldkey. But TotalIssuance is reduced here:
https://github.com/opentensor/subtensor/blob/86b7f6dd702cf173ca98d683d6d01cc402ea9854/pallets/subtensor/src/staking.rs#L685

**Comment by distributedstatemachine** [comment]
closed as fixed
