### ISSUE TITLE
Proxy Pallet Staking Integration

### ISSUE THREAD

**Issue by cisterciansis** [RaoFoundation/subtensor#505]
### Is your feature request related to a problem? Please describe.

Im a normal guy and I will not be able to keep up with dynamic TAO however I want to have a competitive edge when it comes to rewards and maximal returns. 

### Describe the solution you'd like

Hey Team!
My name is Douglas Albert and I am reaching out to you on behalf of the TrustedStake team. We are currently developing a trustless staking service called TrustedStake that aims to optimize staking returns for users by leveraging key performance metrics within the Bittensor ecosystem and token pools.
As we progress with our development, we have encountered a challenge regarding the collection of management and performance fees in a secure and permissionless manner. We would greatly appreciate your guidance and expertise in addressing this matter.
Our current approach utilizes the Substrate proxy pallet, which grants TrustedStake the necessary permissions to stake on behalf of users to whichever subnets are deemed optimal. However, from our understanding, the proxy pallet does not provide direct access to user funds, making it difficult to collect management and performance fees.
We have explored a few potential solutions, but we believe that collaborating with the Open Tensor Foundation could lead to a more robust and efficient approach. Here are a few ideas we have considered:
Partnering with a Validator:
We have explored the possibility of partnering with a validator to implement dynamic take rates per subnet, allowing us to properly distribute the emissions to users.
This approach aims to ensure that users receive the enhanced returns they deserve based on the performance of the specific subnets they are staked in. This method is not ideal and also causes conflicts of interest.
Arbitrage (Robinhood Method):
Another idea is to adopt a model similar to Robinhood, where the service is provided for free to users, and revenue is generated through arbitrage or front-running techniques.
However, we understand that this approach may raise concerns regarding transparency and fairness.
Utilizing the Pallet and Bittensor:
We are keen on finding a solution that leverages the capabilities of the Substrate proxy pallet and the Bittensor ecosystem to maintain a user-friendly, trustless, and non-custodial experience for our users.
We believe that by working closely with the Open Tensor Foundation, we can identify innovative ways to collect fees while adhering to these principles.
Our goal is to develop a fee collection mechanism that is technically sound, secure, and transparent to our users. We value the expertise and insights of the Open Tensor Foundation in navigating this challenge.
We kindly request your guidance on the following aspects:
Are there any existing patterns or best practices within the Bittensor ecosystem that we can leverage to implement a secure and permissionless fee collection mechanism?
Do you have any suggestions or recommendations on how we can utilize the Substrate proxy pallet in combination with other tools or techniques to achieve our goals?
Are there any potential collaborations or partnerships within the Open Tensor Foundation network that could assist us in developing a robust solution?
We would be grateful for any insights, recommendations, or resources you can provide to help us move forward with our development. We believe that by working together, we can create a staking service that benefits the entire Bittensor community.
Thank you for your time and consideration. We look forward to the opportunity to collaborate with the Open Tensor Foundation and contribute to the growth and success of the Bittensor ecosystem.
Best regards, 
Doug 
TrustedStake

**Comment by camfairchild** [comment]
As I mentioned offline, I don't see a good solution to this beyond allowing transfer capability explicitly.

The staking design is like the way it is for security. It wouldn't be good to allow this kind of thing without explicit transfer approval by the user.
