### ISSUE TITLE
Check for disallowed values

### ISSUE THREAD

**Issue by Mananitade** [RaoFoundation/subtensor#566]
https://github.com/opentensor/subtensor/blob/b8364014f36b6a72357881cacb0f3462a3fde5a0/pallets/subtensor/src/epoch.rs#L839

The condition "consensus_high <= consensus_low || alpha_low == 0 || alpha_high == 0" is to check for disallowed values, not for division by zero; moreover, division by zero is handled by saturation arithmetic operators.

**Comment by distributedstatemachine** [comment]
Saturation maths would not prevent division by zero, as this check helps enforce the sanity checks .  I would rather enforce more restrictions (i.e. program defensively) , as in the rare chance a 0 division does get past , the runtime will panic
