### ISSUE TITLE
Make Faucet on Testnet adaptive

### ISSUE THREAD

**Issue by sam0x17** [RaoFoundation/subtensor#580]
The faucet feature allows people to run btcli w faucet to get funds on the testnet. The POW difficulty is really small and causes issues where people abuse the faucet for testnet TAO making it impossible for new people. Lets make the POW faucet on testnet adaptive based on a max rate of new tokens per day/block with an adaptive moving average method.

**Comment by distributedstatemachine** [comment]
closing as no longer valid
