### ISSUE TITLE
Proxy to only transfer free balance. 

### ISSUE THREAD

**Issue by JuanCortez93** [RaoFoundation/subtensor#589]
### Is your feature request related to a problem? Please describe.

I have funds on a wallet, the entire balance is staked. I would like to have a way to access to the free_balance with a new proxy that only can transfer TAO from an account to another. 

With this proxy users can have a wallet protected by 2 proxies : an staking proxy and the proxy proposed. The second proxy cannot unstake, and the first cannot send free balance to another wallet. 

### Describe the solution you'd like

The solution is to code a custom proxy, because it is not one of the default proxy types.

**Comment by camfairchild** [comment]
Implemented in #723
