### ISSUE TITLE
Ban U256::as_u64 and similar functions

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#841]
Conversions like U256::as_u64 can panic if U256 value doesn't fit the bitness. We need to ban use of these functions and recommend replacing with try_into.

**Comment by sam0x17** [comment]
some context:

you will want to look at the custom linting framework in https://github.com/opentensor/subtensor/tree/devnet-ready/support/linting and write a custom lint that finds all  `.as_[primitive here]` method calls and flags them as errors. 

lints are run by running `cargo check` from the root of the repo. You do not need `--workspace`

you can enable the lint by adding it here: https://github.com/opentensor/subtensor/blob/devnet-ready/build.rs#L62-L63

**Comment by eagr** [comment]
I'll give it a shot :)

**Comment by sam0x17** [comment]
ok that is totally fine @eagr, there is also already another community working on it, maybe you two will work together. I will get back to you about that!

**Comment by eagr** [comment]
oops, I didn't know.. btw, I keep the checks to the conversion methods of U256 / U512 to minimize false lint errors. but lmk if that's too specific. is it just me or is `nalgebra` taking forever to build?

**Comment by sam0x17** [comment]
> I keep the checks to the conversion methods of U256 / U512 to minimize false lint errors

that is ideal, excellent

**Comment by sam0x17** [comment]
completed in #846
