### ISSUE TITLE
various issues with `#[pallet_section]` / `#[import_section]`

### ISSUE THREAD

**Issue by sam0x17** [RaoFoundation/subtensor#847]
These are upstream issues with the `#[pallet_section]` / `#[import_section]` syntax that is part of FRAME. It would be extremely helpful if these get fixed upstream, but if OT eventually forks `polkadot-sdk`, wanted to document these here for tracking

* https://github.com/paritytech/polkadot-sdk/issues/5981
* https://github.com/paritytech/polkadot-sdk/issues/5320

**Comment by kianenigma** [comment]
cc @gupnik

**Comment by eagr** [comment]
using the features in pallet section could compile now. try 'em out see if there's any more issues
