### ISSUE TITLE
Add `set_children` and `swap_coldkey/hotkey` to proxy settings.

### ISSUE THREAD

**Issue by vstam1** [RaoFoundation/subtensor#909]
### Is your feature request related to a problem? Please describe.

The current proxy settings are not up to date, and new features are needed to enable safe proxy use for validators. I would like to see either the `set_children` extrinsic added to the `Staking` proxy or a new proxy type. Currently, the most secure option for a `set_children` proxy would be `NonFungibile`, however, this would still allow the swap_coldkey/hotkey functions, making my coldkey vulnerable to attacks by using this proxy type. 

### Describe the solution you'd like

- Add new proxy type for `set_children` or add `set_children` to Staking proxy. 
- Add `swap_coldkey/hotkey` to `NonFungibile` as these functions could be used indirectly to get control over a cold/hot key

**Comment by camfairchild** [comment]
In mainnet from #1016
