### ISSUE TITLE
Check in static analysis for removals from Keys map

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#915]
Check in static analysis that we never remove from `Keys` unless we have matching insert at the same function that inserts with the same map key like in `replace_neuron`:

```rust
// Remove uid_to_replace
Keys::<T>::remove(netuid, uid_to_replace);
...
// Insert with the same key: uid_to_replace
Keys::<T>::insert(netuid, uid_to_replace, new_hotkey.clone());
```

If we remove from `Keys`, epoch function is going to break because it relies on neuron IDs being consecutive. 

Note: Currently we don't have such removals anywhere but `replace_neuron` function, so we can limit such replacements that use `Keys::<T>::remove` to only be present in `replace_neuron`.

**Comment by sam0x17** [comment]
@eagr want this one?

**Comment by eagr** [comment]
* \+ custom lint to forbid `Keys::<T>::remove`
* disable lint for occurrences of `Keys::<T>::remove` in `replace_neuron`

does that sound right? and which is the target branch for dev now?

**Comment by sam0x17** [comment]
that sounds right to me (cc @gregzaitsev), and yes it's `devnet-ready` now 👍🏻

**Comment by eagr** [comment]
anything else? @sam0x17 maybe something slightly more involved that could help me learn more about the project? :)

**Comment by sam0x17** [comment]
> anything else? @sam0x17 maybe something slightly more involved that could help me learn more about the project? :)

if you @ me on the OTF discord would love to talk further :)

same as my gh username
