### ISSUE TITLE
[RAO] Init pool with 1_e9 RAO

### ISSUE THREAD

**Issue by camfairchild** [RaoFoundation/subtensor#969]
### Describe the bug

Right now the subnet pools are initialized with 1 RAO (in TAO and alpha) each. 
This should be 1e9 or 1.0 "TAO" in (TAO and alpha) each. Otherwise we have precision issues when staking/unstaking in the early stages of the subnet's emission schedule.

### To Reproduce

1. initialize a subnet
2. stake to the subnet
3. you will now have 0 alpha (this is not ideal)

### Expected behavior

> 1. initialize a subnet
> 2. stake to the subnet
3. you _should_ now have more than 0 alpha

### Environment

N/A

**Comment by gztensor** [comment]
Waiting for RAO to go on devnet-ready

**Comment by camfairchild** [comment]
closed by #998
